// REDUX ACTION TYPES
export const GET_LIST_BLOGS_ERROR = 'GET_LIST_BLOGS_ERROR'
export const GET_LIST_BLOGS_SUCCESS = 'GET_LIST_BLOGS_SUCCESS'
export const GET_LIST_BLOGS_LOADING = 'GET_LIST_BLOGS_LOADING'

export const GET_BANNER = 'GET_BANNER'
export const GET_METADATA = 'GET_METADATA'
export const POST_CONTACT = 'POST_CONTACT'
